version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:11.10.8-ce.0'
    restart: always
    hostname: 'git.umeme.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://ec2-54-216-27-239.eu-west-1.compute.amazonaws.com'
        # Add any other gitlab.rb configuration here, each on its own line
    ports:
      - '80:80'
      - '443:443'
        #- '22:22'
    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'
    shm_size: '256m'
